# Parte 2: Computación Científica con SciPy

SciPy es una biblioteca esencial en el ecosistema de computación científica de Python, ofreciendo herramientas y técnicas para optimización, álgebra lineal, funciones especiales, estadísticas y más, construidas sobre las operaciones de arreglo de NumPy.

## Optimización

Encontrar los mínimos o máximos de funciones es una piedra angular en muchas disciplinas científicas e ingenieriles. El módulo `optimize` de SciPy proporciona un conjunto completo de algoritmos para la optimización de funciones.

### Minimización sin Restricciones: Función de Rosenbrock

La función de Rosenbrock, a menudo utilizada como un problema de prueba de rendimiento para algoritmos de optimización, es una función no convexa utilizada para evaluar el rendimiento de los algoritmos de optimización.


In [24]:
from scipy.optimize import minimize

def rosenbrock(x):
    """La función de Rosenbrock"""
    return (1 - x[0])**2 + 100 * (x[1] - x[0]**2)**2

x0 = [0, 0]  # Adivinanza inicial
res = minimize(rosenbrock, x0)
res

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 2.8439915001532524e-11
        x: [ 1.000e+00  1.000e+00]
      nit: 19
      jac: [ 3.987e-06 -2.844e-06]
 hess_inv: [[ 4.948e-01  9.896e-01]
            [ 9.896e-01  1.984e+00]]
     nfev: 72
     njev: 24

### Optimización con Restricciones: Restricciones Lineales

En muchos problemas del mundo real, el espacio de soluciones está restringido. SciPy maneja tales problemas de manera eficiente, permitiendo límites y restricciones en la solución.

In [4]:
def objetivo(x):
    """Función objetivo a minimizar"""
    return x[0]**2 + x[1]**2

# Restricciones definidas como desigualdades
constraints = [{'type': 'ineq', 'fun': lambda x:  x[0] - 2},
               {'type': 'ineq', 'fun': lambda x: -x[0] - 2},
               {'type': 'ineq', 'fun': lambda x:  x[1] - 2},
               {'type': 'ineq', 'fun': lambda x: -x[1] - 2}]

x0 = [0.5, 0.5]  # Adivinanza inicial
res = minimize(objetivo, x0, constraints=constraints)
res

 message: Positive directional derivative for linesearch
 success: False
  status: 8
     fun: 0.499999999999979
       x: [ 5.000e-01  5.000e-01]
     nit: 10
     jac: [ 1.000e+00  1.000e+00]
    nfev: 62
    njev: 6

## Álgebra Lineal

SciPy mejora las capacidades de álgebra lineal de NumPy con funciones más avanzadas, cruciales para resolver sistemas de ecuaciones, problemas de valores propios y más.

### Valores y Vectores Propios

Los valores y vectores propios juegan un papel crucial en el análisis de estabilidad de sistemas, en mecánica cuántica y en muchas otras áreas.

In [6]:
import numpy as np
from scipy.linalg import eig

A = np.array([[1, 2], [3, 4]])  # Definir una matriz
valores_propios, vectores_propios = eig(A)

### Descomposición en Valores Singulares (SVD)

SVD es ampliamente utilizado en procesamiento de señales y estadísticas para la reducción de datos y la reducción de ruido.

In [8]:
from scipy.linalg import svd

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Definir una matriz
U, s, VT = svd(A)
U, s, VT

(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [-0.40824829,  0.81649658, -0.40824829]]))

## Funciones Especiales

Las funciones especiales son ubicuas en física, ingeniería y matemáticas. El módulo `special` de SciPy proporciona implementaciones eficientes de estas funciones.

### Función Gamma

La función Gamma extiende la función factorial a argumentos de números complejos y reales, desempeñando un papel clave en varias áreas de las matemáticas.

In [9]:
from scipy.special import gamma

x = 0.5  # Valor
resultado = gamma(x)

### Función de Error

La función de error es integral para los cálculos en estadísticas, especialmente en las funciones de distribución acumulativa de variables normales.


In [10]:
from scipy.special import erf

x = 1.0  # Valor
resultado = erf(x)

## Estadísticas

El módulo `stats` de SciPy está equipado

 con una amplia gama de distribuciones de probabilidad y una creciente biblioteca de funciones estadísticas.

### Estadísticas Descriptivas

Las estadísticas descriptivas proporcionan medidas resumidas que describen las características principales de un conjunto de datos, ofreciendo información sobre la forma y la dispersión de la distribución de datos.


In [11]:
from scipy import stats

datos = np.random.normal(loc=0, scale=1, size=100)  # Generar datos aleatorios
media, std = stats.norm.fit(datos)

### Pruebas de Hipótesis: Prueba T

Las pruebas de hipótesis se utilizan para inferir las propiedades de una población a partir de una muestra. La prueba t evalúa si las medias de dos grupos son estadísticamente diferentes.


In [12]:
datos1 = np.random.normal(loc=0, scale=1, size=100)
datos2 = np.random.normal(loc=0.5, scale=1.5, size=100)

t_stat, p_val = stats.ttest_ind(datos1, datos2)
t_stat, p_val

(-1.9727045057127812, 0.0499210077231055)

## Arreglos Dispersos

Los arreglos dispersos son una forma eficiente de almacenar y procesar datos que contienen un número significativo de ceros.

### Creación de Matrices Dispersas

Las matrices dispersas son cruciales para el almacenamiento eficiente y el cálculo en grandes conjuntos de datos o matrices donde la mayoría de los elementos son cero.

In [13]:
from scipy.sparse import coo_matrix

A = np.array([[1, 0, 0], [0, 0, 3], [4, 0, 5]])  # Definir una matriz
S = coo_matrix(A)

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in COOrdinate format>

## Comparación de Rendimiento: SciPy vs. Python Puro

Una ventaja crítica de usar SciPy en la computación científica es su rendimiento, particularmente para operaciones que son computacionalmente intensivas. Para ilustrar esto, vamos a comparar la eficiencia de resolver un gran sistema de ecuaciones lineales usando las funciones optimizadas de SciPy versus una implementación en Python puro.

### Resolviendo un Gran Sistema de Ecuaciones Lineales

Resolver ecuaciones lineales es una tarea común en la computación científica. Las ganancias de eficiencia al usar SciPy se hacen evidentes con grandes sistemas.

#### Solucionador de Ecuaciones Lineales de SciPy

`linalg.solve` de SciPy está altamente optimizado para resolver sistemas de ecuaciones lineales y puede manejar matrices grandes de manera eficiente.


In [23]:
from scipy.linalg import solve
import numpy as np
import time

# Generar una matriz y vector aleatorios grandes (por ejemplo, 1000x1000)
A = np.random.rand(1000, 1000)
b = np.random.rand(1000)

# Iniciar el cronómetro para SciPy solve
start_time = time.time()

# Resolver el sistema
x_scipy = solve(A, b)

# Detener el cronómetro
scipy_duration = time.time() - start_time
scipy_duration

0.0859978199005127

#### Solucionador de Ecuaciones Lineales en Python Puro (Eliminación Gaussiana)

Una implementación ingenua en Python usando la Eliminación Gaussiana es mucho menos eficiente, especialmente para matrices grandes.

In [22]:
def gaussian_elimination(A, b):
    n = len(A)
    # Eliminación hacia adelante
    for i in range(n):
        max_elem = abs(A[i][i])
        max_row = i
        for k in range(i+1, n):
            if abs(A[k][i]) > max_elem:
                max_elem = abs(A[k][i])
                max_row = k
        A[max_row], A[i] = A[i], A[max_row]
        b[max_row], b[i] = b[i], b[max_row]
        for k in range(i+1, n):
            c = -A[k][i]/A[i][i]
            for j in range(i, n):
                A[k][j] += c * A[i][j]
            b[k] += c * b[i]
    # Sustitución hacia atrás
    x = [0 for _ in range(n)]
    for i in range(n-1, -1, -1):
        x[i] = b[i] / A[i][i]
        for k in range(i-1, -1, -1):
            b[k] -= A[k][i] * x[i]
    return x

# Convertir arreglos de numpy a listas para Python puro
A_list = A.tolist()
b_list = b.tolist()

# Iniciar el cronómetro para la solución en Python
start_python_time = time.time()

# Resolver usando Python puro
x_python = gaussian_elimination(A_list, b_list)

# Detener el cronómetro
python_duration = time.time() - start_python_time
print(python_duration)

18.513363122940063


---

### Problemas:

1. **Optimizaciób**:
   Considera el siguiente problema de optimización:
   Maximiza \( f(x) = x^2 - 4x + 4 \) sujeto a la restricción \( x \geq 2 \).

2. **Álgebra Lineal**:
   Resuelve el sistema de ecuaciones lineales:
   \[
   \begin{align*}
   2x + 3y &= 5 \\
   4x - 2y &= -6
   \end{align*}
   \]

3. **Funciones Especiales**:
   Calcula el valor de la función de Bessel de primer tipo de orden 2 en \( x = 1.5 \).

4. **Estadísticas**:
   Realiza una prueba de hipótesis para determinar si dos conjuntos de datos son significativamente diferentes, dados los siguientes datos:
   - Conjunto 1: \( [4, 5, 7, 8, 9] \)
   - Conjunto 2: \( [7, 6, 8, 9, 10] \)

5. **Arreglos Dispersos**:
   Crea una matriz dispersa grande (por ejemplo, 1000x1000) con un patrón específico de elementos diferentes de cero y calcula su determinante.

6. **Optimización**:
   Considera el siguiente problema de optimización restringida:
   Minimiza \( f(x, y) = x^2 + y^2 \) sujeto a las restricciones \( x^2 + y^2 <= 1 \) y \( x + y >= 1 \).
